{ inputs, self, ... }: {
  imports = [ inputs.vaultix.flakeModules.default ];

  flake.vaultix = {
    # Hosts whose secrets vaultix manages (used by the renc/edit apps).
    nodes = self.nixosConfigurations;
    # Master age identity; an absolute path string so it never enters the Nix
    # store. Must exist on every machine that runs `nix run .#vaultix...` apps.
    identity = "/home/onyx/.config/vaultix/identity";
    # Per-host re-encrypted secrets (generated by `renc`, commit it).
    cache = "./secrets/cache";
    defaultSecretDirectory = "./secrets";
  };

  flake.modules.nixos.vaultix =
    { ... }: {
      imports = [ inputs.vaultix.nixosModules.default ];

      # Vaultix decryption runs as a systemd unit and requires systemd-based
      # user/group creation.
      services.userborn.enable = true;
    };
}
